In [3]:
import chess
import tensorflow as tf
import numpy as np
import utils

model = tf.keras.models.load_model("/home/marcello/github/ChessBreaker/old_stuff/tmp_first_model/checkpoint-44.hdf5")

board = chess.Board()

board_history = [board.fen()[:-6]]
planes = None

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

/home/marcello/github/ChessBreaker/env/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py:303: UserWarning: model is not loaded, but a Lambda layer uses it. It may cause errors.
  function = cls._parse_function_from_config(config, custom_objects,


In [4]:
# planes = utils.update_planes(planes, board, board_history)
# move = chess.Move.from_uci("e2e4")
# board.push(move)
# board_history.append(board.fen()[:-6])
# board

In [5]:
planes = utils.update_planes(planes, board, board_history)
i = 0
j = 0
output_array = np.zeros([8, 8, 73], dtype=np.float32)
move = chess.Move.from_uci("e2e3")
# mask = utils.mask_moves([move])[0]
# output_array[mask[0], mask[1], mask[2]] = 1

board.push(move)
board_history.append(board.fen()[:-6])
planes = utils.update_planes(planes, board, board_history)

In [124]:
print(i)
print(planes[:, :, i])
i+=1

118
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(j)
print(output_array[:, :, j])
j+=1

In [ ]:
planes = utils.update_planes(planes, board, board_history)
legal_moves = board.legal_moves
action_v, outcome = model(tf.expand_dims(planes, axis=0))
action_v = action_v[0]
# print(np.shape(action_v))
print(outcome[0].numpy())

idxs = utils.mask_moves(legal_moves)
move_value = []
for move, idx in zip(legal_moves, idxs):
    move_value.append(action_v[idx[0], idx[1], idx[2]].numpy())

move_value = softmax(move_value)

high_av = -100
best_move = None
for move, value in zip(legal_moves, move_value):
    if value > high_av:
        # print(move, value)
        high_av = value
        best_move = move

board.push(best_move)
board_history.append(board.fen()[:-6])
print(board.outcome(claim_draw=True).outcome)
board

In [ ]:
print(utils.outcome(board.outcome(claim_draw=True).result()))